//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaddalenaUnitTest.MaddalenaServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/Maddalena.Public")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AccessFailedCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EmailConfirmedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool LockoutEnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> LockoutEndDateUtcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PhoneNumberConfirmedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TwoFactorEnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AccessFailedCount {
            get {
                return this.AccessFailedCountField;
            }
            set {
                if ((this.AccessFailedCountField.Equals(value) != true)) {
                    this.AccessFailedCountField = value;
                    this.RaisePropertyChanged("AccessFailedCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EmailConfirmed {
            get {
                return this.EmailConfirmedField;
            }
            set {
                if ((this.EmailConfirmedField.Equals(value) != true)) {
                    this.EmailConfirmedField = value;
                    this.RaisePropertyChanged("EmailConfirmed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool LockoutEnabled {
            get {
                return this.LockoutEnabledField;
            }
            set {
                if ((this.LockoutEnabledField.Equals(value) != true)) {
                    this.LockoutEnabledField = value;
                    this.RaisePropertyChanged("LockoutEnabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LockoutEndDateUtc {
            get {
                return this.LockoutEndDateUtcField;
            }
            set {
                if ((this.LockoutEndDateUtcField.Equals(value) != true)) {
                    this.LockoutEndDateUtcField = value;
                    this.RaisePropertyChanged("LockoutEndDateUtc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PhoneNumberConfirmed {
            get {
                return this.PhoneNumberConfirmedField;
            }
            set {
                if ((this.PhoneNumberConfirmedField.Equals(value) != true)) {
                    this.PhoneNumberConfirmedField = value;
                    this.RaisePropertyChanged("PhoneNumberConfirmed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TwoFactorEnabled {
            get {
                return this.TwoFactorEnabledField;
            }
            set {
                if ((this.TwoFactorEnabledField.Equals(value) != true)) {
                    this.TwoFactorEnabledField = value;
                    this.RaisePropertyChanged("TwoFactorEnabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Group", Namespace="http://schemas.datacontract.org/2004/07/Maddalena.Model")]
    [System.SerializableAttribute()]
    public partial class Group : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MaddalenaUnitTest.MaddalenaServiceReference.User1 AspNetUsersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MaddalenaUnitTest.MaddalenaServiceReference.GroupMembership[] GroupMembershipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MaddalenaUnitTest.MaddalenaServiceReference.GroupPost[] GroupPostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LinkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OwnerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MaddalenaUnitTest.MaddalenaServiceReference.User1 AspNetUsers {
            get {
                return this.AspNetUsersField;
            }
            set {
                if ((object.ReferenceEquals(this.AspNetUsersField, value) != true)) {
                    this.AspNetUsersField = value;
                    this.RaisePropertyChanged("AspNetUsers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MaddalenaUnitTest.MaddalenaServiceReference.GroupMembership[] GroupMembership {
            get {
                return this.GroupMembershipField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupMembershipField, value) != true)) {
                    this.GroupMembershipField = value;
                    this.RaisePropertyChanged("GroupMembership");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MaddalenaUnitTest.MaddalenaServiceReference.GroupPost[] GroupPost {
            get {
                return this.GroupPostField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupPostField, value) != true)) {
                    this.GroupPostField = value;
                    this.RaisePropertyChanged("GroupPost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Link {
            get {
                return this.LinkField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkField, value) != true)) {
                    this.LinkField = value;
                    this.RaisePropertyChanged("Link");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Owner {
            get {
                return this.OwnerField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnerField, value) != true)) {
                    this.OwnerField = value;
                    this.RaisePropertyChanged("Owner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/Maddalena.Model")]
    [System.SerializableAttribute()]
    public partial class User1 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AccessFailedCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MaddalenaUnitTest.MaddalenaServiceReference.ApiKey[] ApiKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MaddalenaUnitTest.MaddalenaServiceReference.AspNetRoles[] AspNetRolesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MaddalenaUnitTest.MaddalenaServiceReference.AspNetUserClaims[] AspNetUserClaimsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EmailConfirmedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MaddalenaUnitTest.MaddalenaServiceReference.Group[] GroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MaddalenaUnitTest.MaddalenaServiceReference.GroupMembership[] GroupMembershipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MaddalenaUnitTest.MaddalenaServiceReference.GroupPost[] GroupPostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool LockoutEnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> LockoutEndDateUtcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordHashField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PhoneNumberConfirmedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecurityStampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TwoFactorEnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AccessFailedCount {
            get {
                return this.AccessFailedCountField;
            }
            set {
                if ((this.AccessFailedCountField.Equals(value) != true)) {
                    this.AccessFailedCountField = value;
                    this.RaisePropertyChanged("AccessFailedCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MaddalenaUnitTest.MaddalenaServiceReference.ApiKey[] ApiKey {
            get {
                return this.ApiKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.ApiKeyField, value) != true)) {
                    this.ApiKeyField = value;
                    this.RaisePropertyChanged("ApiKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MaddalenaUnitTest.MaddalenaServiceReference.AspNetRoles[] AspNetRoles {
            get {
                return this.AspNetRolesField;
            }
            set {
                if ((object.ReferenceEquals(this.AspNetRolesField, value) != true)) {
                    this.AspNetRolesField = value;
                    this.RaisePropertyChanged("AspNetRoles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MaddalenaUnitTest.MaddalenaServiceReference.AspNetUserClaims[] AspNetUserClaims {
            get {
                return this.AspNetUserClaimsField;
            }
            set {
                if ((object.ReferenceEquals(this.AspNetUserClaimsField, value) != true)) {
                    this.AspNetUserClaimsField = value;
                    this.RaisePropertyChanged("AspNetUserClaims");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EmailConfirmed {
            get {
                return this.EmailConfirmedField;
            }
            set {
                if ((this.EmailConfirmedField.Equals(value) != true)) {
                    this.EmailConfirmedField = value;
                    this.RaisePropertyChanged("EmailConfirmed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MaddalenaUnitTest.MaddalenaServiceReference.Group[] Group {
            get {
                return this.GroupField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupField, value) != true)) {
                    this.GroupField = value;
                    this.RaisePropertyChanged("Group");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MaddalenaUnitTest.MaddalenaServiceReference.GroupMembership[] GroupMembership {
            get {
                return this.GroupMembershipField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupMembershipField, value) != true)) {
                    this.GroupMembershipField = value;
                    this.RaisePropertyChanged("GroupMembership");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MaddalenaUnitTest.MaddalenaServiceReference.GroupPost[] GroupPost {
            get {
                return this.GroupPostField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupPostField, value) != true)) {
                    this.GroupPostField = value;
                    this.RaisePropertyChanged("GroupPost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool LockoutEnabled {
            get {
                return this.LockoutEnabledField;
            }
            set {
                if ((this.LockoutEnabledField.Equals(value) != true)) {
                    this.LockoutEnabledField = value;
                    this.RaisePropertyChanged("LockoutEnabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LockoutEndDateUtc {
            get {
                return this.LockoutEndDateUtcField;
            }
            set {
                if ((this.LockoutEndDateUtcField.Equals(value) != true)) {
                    this.LockoutEndDateUtcField = value;
                    this.RaisePropertyChanged("LockoutEndDateUtc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PasswordHash {
            get {
                return this.PasswordHashField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordHashField, value) != true)) {
                    this.PasswordHashField = value;
                    this.RaisePropertyChanged("PasswordHash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PhoneNumberConfirmed {
            get {
                return this.PhoneNumberConfirmedField;
            }
            set {
                if ((this.PhoneNumberConfirmedField.Equals(value) != true)) {
                    this.PhoneNumberConfirmedField = value;
                    this.RaisePropertyChanged("PhoneNumberConfirmed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecurityStamp {
            get {
                return this.SecurityStampField;
            }
            set {
                if ((object.ReferenceEquals(this.SecurityStampField, value) != true)) {
                    this.SecurityStampField = value;
                    this.RaisePropertyChanged("SecurityStamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TwoFactorEnabled {
            get {
                return this.TwoFactorEnabledField;
            }
            set {
                if ((this.TwoFactorEnabledField.Equals(value) != true)) {
                    this.TwoFactorEnabledField = value;
                    this.RaisePropertyChanged("TwoFactorEnabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GroupMembership", Namespace="http://schemas.datacontract.org/2004/07/Maddalena.Model")]
    [System.SerializableAttribute()]
    public partial class GroupMembership : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MaddalenaUnitTest.MaddalenaServiceReference.User1 AspNetUsersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MaddalenaUnitTest.MaddalenaServiceReference.Group GroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long GroupIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MaddalenaUnitTest.MaddalenaServiceReference.User1 AspNetUsers {
            get {
                return this.AspNetUsersField;
            }
            set {
                if ((object.ReferenceEquals(this.AspNetUsersField, value) != true)) {
                    this.AspNetUsersField = value;
                    this.RaisePropertyChanged("AspNetUsers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MaddalenaUnitTest.MaddalenaServiceReference.Group Group {
            get {
                return this.GroupField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupField, value) != true)) {
                    this.GroupField = value;
                    this.RaisePropertyChanged("Group");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long GroupId {
            get {
                return this.GroupIdField;
            }
            set {
                if ((this.GroupIdField.Equals(value) != true)) {
                    this.GroupIdField = value;
                    this.RaisePropertyChanged("GroupId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIdField, value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GroupPost", Namespace="http://schemas.datacontract.org/2004/07/Maddalena.Model")]
    [System.SerializableAttribute()]
    public partial class GroupPost : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MaddalenaUnitTest.MaddalenaServiceReference.User1 AspNetUsersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MaddalenaUnitTest.MaddalenaServiceReference.Group GroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long GroupIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long LikesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RenderedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimestampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MaddalenaUnitTest.MaddalenaServiceReference.User1 AspNetUsers {
            get {
                return this.AspNetUsersField;
            }
            set {
                if ((object.ReferenceEquals(this.AspNetUsersField, value) != true)) {
                    this.AspNetUsersField = value;
                    this.RaisePropertyChanged("AspNetUsers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MaddalenaUnitTest.MaddalenaServiceReference.Group Group {
            get {
                return this.GroupField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupField, value) != true)) {
                    this.GroupField = value;
                    this.RaisePropertyChanged("Group");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long GroupId {
            get {
                return this.GroupIdField;
            }
            set {
                if ((this.GroupIdField.Equals(value) != true)) {
                    this.GroupIdField = value;
                    this.RaisePropertyChanged("GroupId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Likes {
            get {
                return this.LikesField;
            }
            set {
                if ((this.LikesField.Equals(value) != true)) {
                    this.LikesField = value;
                    this.RaisePropertyChanged("Likes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rendered {
            get {
                return this.RenderedField;
            }
            set {
                if ((object.ReferenceEquals(this.RenderedField, value) != true)) {
                    this.RenderedField = value;
                    this.RaisePropertyChanged("Rendered");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Source {
            get {
                return this.SourceField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceField, value) != true)) {
                    this.SourceField = value;
                    this.RaisePropertyChanged("Source");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Timestamp {
            get {
                return this.TimestampField;
            }
            set {
                if ((this.TimestampField.Equals(value) != true)) {
                    this.TimestampField = value;
                    this.RaisePropertyChanged("Timestamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIdField, value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApiKey", Namespace="http://schemas.datacontract.org/2004/07/Maddalena.Model")]
    [System.SerializableAttribute()]
    public partial class ApiKey : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MaddalenaUnitTest.MaddalenaServiceReference.User1 AspNetUsersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CallsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedAtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastUseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MaddalenaUnitTest.MaddalenaServiceReference.User1 AspNetUsers {
            get {
                return this.AspNetUsersField;
            }
            set {
                if ((object.ReferenceEquals(this.AspNetUsersField, value) != true)) {
                    this.AspNetUsersField = value;
                    this.RaisePropertyChanged("AspNetUsers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Calls {
            get {
                return this.CallsField;
            }
            set {
                if ((this.CallsField.Equals(value) != true)) {
                    this.CallsField = value;
                    this.RaisePropertyChanged("Calls");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedAt {
            get {
                return this.CreatedAtField;
            }
            set {
                if ((this.CreatedAtField.Equals(value) != true)) {
                    this.CreatedAtField = value;
                    this.RaisePropertyChanged("CreatedAt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastUse {
            get {
                return this.LastUseField;
            }
            set {
                if ((this.LastUseField.Equals(value) != true)) {
                    this.LastUseField = value;
                    this.RaisePropertyChanged("LastUse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIdField, value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AspNetRoles", Namespace="http://schemas.datacontract.org/2004/07/Maddalena.Model")]
    [System.SerializableAttribute()]
    public partial class AspNetRoles : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MaddalenaUnitTest.MaddalenaServiceReference.User1[] AspNetUsersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MaddalenaUnitTest.MaddalenaServiceReference.User1[] AspNetUsers {
            get {
                return this.AspNetUsersField;
            }
            set {
                if ((object.ReferenceEquals(this.AspNetUsersField, value) != true)) {
                    this.AspNetUsersField = value;
                    this.RaisePropertyChanged("AspNetUsers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AspNetUserClaims", Namespace="http://schemas.datacontract.org/2004/07/Maddalena.Model")]
    [System.SerializableAttribute()]
    public partial class AspNetUserClaims : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MaddalenaUnitTest.MaddalenaServiceReference.User1 AspNetUsersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaimTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaimValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MaddalenaUnitTest.MaddalenaServiceReference.User1 AspNetUsers {
            get {
                return this.AspNetUsersField;
            }
            set {
                if ((object.ReferenceEquals(this.AspNetUsersField, value) != true)) {
                    this.AspNetUsersField = value;
                    this.RaisePropertyChanged("AspNetUsers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClaimType {
            get {
                return this.ClaimTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaimTypeField, value) != true)) {
                    this.ClaimTypeField = value;
                    this.RaisePropertyChanged("ClaimType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClaimValue {
            get {
                return this.ClaimValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaimValueField, value) != true)) {
                    this.ClaimValueField = value;
                    this.RaisePropertyChanged("ClaimValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIdField, value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MaddalenaServiceReference.IApiKeyService")]
    public interface IApiKeyService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApiKeyService/Create", ReplyAction="http://tempuri.org/IApiKeyService/CreateResponse")]
        string Create(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApiKeyService/Create", ReplyAction="http://tempuri.org/IApiKeyService/CreateResponse")]
        System.Threading.Tasks.Task<string> CreateAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApiKeyService/Validate", ReplyAction="http://tempuri.org/IApiKeyService/ValidateResponse")]
        bool Validate(string apikey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApiKeyService/Validate", ReplyAction="http://tempuri.org/IApiKeyService/ValidateResponse")]
        System.Threading.Tasks.Task<bool> ValidateAsync(string apikey);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IApiKeyServiceChannel : MaddalenaUnitTest.MaddalenaServiceReference.IApiKeyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ApiKeyServiceClient : System.ServiceModel.ClientBase<MaddalenaUnitTest.MaddalenaServiceReference.IApiKeyService>, MaddalenaUnitTest.MaddalenaServiceReference.IApiKeyService {
        
        public ApiKeyServiceClient() {
        }
        
        public ApiKeyServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ApiKeyServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApiKeyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApiKeyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Create(string username) {
            return base.Channel.Create(username);
        }
        
        public System.Threading.Tasks.Task<string> CreateAsync(string username) {
            return base.Channel.CreateAsync(username);
        }
        
        public bool Validate(string apikey) {
            return base.Channel.Validate(apikey);
        }
        
        public System.Threading.Tasks.Task<bool> ValidateAsync(string apikey) {
            return base.Channel.ValidateAsync(apikey);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MaddalenaServiceReference.IUserService")]
    public interface IUserService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Exist", ReplyAction="http://tempuri.org/IUserService/ExistResponse")]
        bool Exist(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Exist", ReplyAction="http://tempuri.org/IUserService/ExistResponse")]
        System.Threading.Tasks.Task<bool> ExistAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/ByName", ReplyAction="http://tempuri.org/IUserService/ByNameResponse")]
        MaddalenaUnitTest.MaddalenaServiceReference.User ByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/ByName", ReplyAction="http://tempuri.org/IUserService/ByNameResponse")]
        System.Threading.Tasks.Task<MaddalenaUnitTest.MaddalenaServiceReference.User> ByNameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/ByEmail", ReplyAction="http://tempuri.org/IUserService/ByEmailResponse")]
        MaddalenaUnitTest.MaddalenaServiceReference.User ByEmail(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/ByEmail", ReplyAction="http://tempuri.org/IUserService/ByEmailResponse")]
        System.Threading.Tasks.Task<MaddalenaUnitTest.MaddalenaServiceReference.User> ByEmailAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/ByPhoneNumber", ReplyAction="http://tempuri.org/IUserService/ByPhoneNumberResponse")]
        MaddalenaUnitTest.MaddalenaServiceReference.User ByPhoneNumber(string number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/ByPhoneNumber", ReplyAction="http://tempuri.org/IUserService/ByPhoneNumberResponse")]
        System.Threading.Tasks.Task<MaddalenaUnitTest.MaddalenaServiceReference.User> ByPhoneNumberAsync(string number);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserServiceChannel : MaddalenaUnitTest.MaddalenaServiceReference.IUserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceClient : System.ServiceModel.ClientBase<MaddalenaUnitTest.MaddalenaServiceReference.IUserService>, MaddalenaUnitTest.MaddalenaServiceReference.IUserService {
        
        public UserServiceClient() {
        }
        
        public UserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Exist(string name) {
            return base.Channel.Exist(name);
        }
        
        public System.Threading.Tasks.Task<bool> ExistAsync(string name) {
            return base.Channel.ExistAsync(name);
        }
        
        public MaddalenaUnitTest.MaddalenaServiceReference.User ByName(string name) {
            return base.Channel.ByName(name);
        }
        
        public System.Threading.Tasks.Task<MaddalenaUnitTest.MaddalenaServiceReference.User> ByNameAsync(string name) {
            return base.Channel.ByNameAsync(name);
        }
        
        public MaddalenaUnitTest.MaddalenaServiceReference.User ByEmail(string email) {
            return base.Channel.ByEmail(email);
        }
        
        public System.Threading.Tasks.Task<MaddalenaUnitTest.MaddalenaServiceReference.User> ByEmailAsync(string email) {
            return base.Channel.ByEmailAsync(email);
        }
        
        public MaddalenaUnitTest.MaddalenaServiceReference.User ByPhoneNumber(string number) {
            return base.Channel.ByPhoneNumber(number);
        }
        
        public System.Threading.Tasks.Task<MaddalenaUnitTest.MaddalenaServiceReference.User> ByPhoneNumberAsync(string number) {
            return base.Channel.ByPhoneNumberAsync(number);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MaddalenaServiceReference.IGroupService")]
    public interface IGroupService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/CreateGroup", ReplyAction="http://tempuri.org/IGroupService/CreateGroupResponse")]
        bool CreateGroup(string apiKey, MaddalenaUnitTest.MaddalenaServiceReference.Group group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/CreateGroup", ReplyAction="http://tempuri.org/IGroupService/CreateGroupResponse")]
        System.Threading.Tasks.Task<bool> CreateGroupAsync(string apiKey, MaddalenaUnitTest.MaddalenaServiceReference.Group group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/ById", ReplyAction="http://tempuri.org/IGroupService/ByIdResponse")]
        MaddalenaUnitTest.MaddalenaServiceReference.Group ById(string apiKey, long groupid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/ById", ReplyAction="http://tempuri.org/IGroupService/ByIdResponse")]
        System.Threading.Tasks.Task<MaddalenaUnitTest.MaddalenaServiceReference.Group> ByIdAsync(string apiKey, long groupid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/UpdateGroup", ReplyAction="http://tempuri.org/IGroupService/UpdateGroupResponse")]
        bool UpdateGroup(string apiKey, MaddalenaUnitTest.MaddalenaServiceReference.Group group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/UpdateGroup", ReplyAction="http://tempuri.org/IGroupService/UpdateGroupResponse")]
        System.Threading.Tasks.Task<bool> UpdateGroupAsync(string apiKey, MaddalenaUnitTest.MaddalenaServiceReference.Group group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/DeleteGroup", ReplyAction="http://tempuri.org/IGroupService/DeleteGroupResponse")]
        bool DeleteGroup(string apiKey, long groupid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/DeleteGroup", ReplyAction="http://tempuri.org/IGroupService/DeleteGroupResponse")]
        System.Threading.Tasks.Task<bool> DeleteGroupAsync(string apiKey, long groupid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/GroupMembersCount", ReplyAction="http://tempuri.org/IGroupService/GroupMembersCountResponse")]
        int GroupMembersCount(string apiKey, long groupid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/GroupMembersCount", ReplyAction="http://tempuri.org/IGroupService/GroupMembersCountResponse")]
        System.Threading.Tasks.Task<int> GroupMembersCountAsync(string apiKey, long groupid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/GroupMembers", ReplyAction="http://tempuri.org/IGroupService/GroupMembersResponse")]
        MaddalenaUnitTest.MaddalenaServiceReference.User1[] GroupMembers(string apiKey, long groupid, int page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/GroupMembers", ReplyAction="http://tempuri.org/IGroupService/GroupMembersResponse")]
        System.Threading.Tasks.Task<MaddalenaUnitTest.MaddalenaServiceReference.User1[]> GroupMembersAsync(string apiKey, long groupid, int page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/JoinGroup", ReplyAction="http://tempuri.org/IGroupService/JoinGroupResponse")]
        bool JoinGroup(string apiKey, long groupid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/JoinGroup", ReplyAction="http://tempuri.org/IGroupService/JoinGroupResponse")]
        System.Threading.Tasks.Task<bool> JoinGroupAsync(string apiKey, long groupid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/LeaveGroup", ReplyAction="http://tempuri.org/IGroupService/LeaveGroupResponse")]
        void LeaveGroup(string apiKey, long groupid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/LeaveGroup", ReplyAction="http://tempuri.org/IGroupService/LeaveGroupResponse")]
        System.Threading.Tasks.Task LeaveGroupAsync(string apiKey, long groupid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/Recents", ReplyAction="http://tempuri.org/IGroupService/RecentsResponse")]
        MaddalenaUnitTest.MaddalenaServiceReference.GroupPost[] Recents(string apiKey, long groupid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/Recents", ReplyAction="http://tempuri.org/IGroupService/RecentsResponse")]
        System.Threading.Tasks.Task<MaddalenaUnitTest.MaddalenaServiceReference.GroupPost[]> RecentsAsync(string apiKey, long groupid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/Tops", ReplyAction="http://tempuri.org/IGroupService/TopsResponse")]
        MaddalenaUnitTest.MaddalenaServiceReference.GroupPost[] Tops(string apiKey, long groupid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/Tops", ReplyAction="http://tempuri.org/IGroupService/TopsResponse")]
        System.Threading.Tasks.Task<MaddalenaUnitTest.MaddalenaServiceReference.GroupPost[]> TopsAsync(string apiKey, long groupid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/List", ReplyAction="http://tempuri.org/IGroupService/ListResponse")]
        MaddalenaUnitTest.MaddalenaServiceReference.GroupPost[] List(string apiKey, long groupid, int page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/List", ReplyAction="http://tempuri.org/IGroupService/ListResponse")]
        System.Threading.Tasks.Task<MaddalenaUnitTest.MaddalenaServiceReference.GroupPost[]> ListAsync(string apiKey, long groupid, int page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/OfUser", ReplyAction="http://tempuri.org/IGroupService/OfUserResponse")]
        MaddalenaUnitTest.MaddalenaServiceReference.GroupPost[] OfUser(string apiKey, long groupid, string userid, int page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/OfUser", ReplyAction="http://tempuri.org/IGroupService/OfUserResponse")]
        System.Threading.Tasks.Task<MaddalenaUnitTest.MaddalenaServiceReference.GroupPost[]> OfUserAsync(string apiKey, long groupid, string userid, int page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/Post", ReplyAction="http://tempuri.org/IGroupService/PostResponse")]
        bool Post(string apiKey, [System.ServiceModel.MessageParameterAttribute(Name="post")] MaddalenaUnitTest.MaddalenaServiceReference.GroupPost post1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/Post", ReplyAction="http://tempuri.org/IGroupService/PostResponse")]
        System.Threading.Tasks.Task<bool> PostAsync(string apiKey, MaddalenaUnitTest.MaddalenaServiceReference.GroupPost post);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/Delete", ReplyAction="http://tempuri.org/IGroupService/DeleteResponse")]
        bool Delete(string apiKey, long postId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/Delete", ReplyAction="http://tempuri.org/IGroupService/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(string apiKey, long postId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/Ban", ReplyAction="http://tempuri.org/IGroupService/BanResponse")]
        bool Ban(string apiKey, long groupid, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/Ban", ReplyAction="http://tempuri.org/IGroupService/BanResponse")]
        System.Threading.Tasks.Task<bool> BanAsync(string apiKey, long groupid, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/MakeModerator", ReplyAction="http://tempuri.org/IGroupService/MakeModeratorResponse")]
        bool MakeModerator(string apiKey, long groupid, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/MakeModerator", ReplyAction="http://tempuri.org/IGroupService/MakeModeratorResponse")]
        System.Threading.Tasks.Task<bool> MakeModeratorAsync(string apiKey, long groupid, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/MakeAdmin", ReplyAction="http://tempuri.org/IGroupService/MakeAdminResponse")]
        bool MakeAdmin(string apiKey, long groupid, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/MakeAdmin", ReplyAction="http://tempuri.org/IGroupService/MakeAdminResponse")]
        System.Threading.Tasks.Task<bool> MakeAdminAsync(string apiKey, long groupid, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/MakeOwner", ReplyAction="http://tempuri.org/IGroupService/MakeOwnerResponse")]
        bool MakeOwner(string apiKey, long groupid, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGroupService/MakeOwner", ReplyAction="http://tempuri.org/IGroupService/MakeOwnerResponse")]
        System.Threading.Tasks.Task<bool> MakeOwnerAsync(string apiKey, long groupid, string username);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGroupServiceChannel : MaddalenaUnitTest.MaddalenaServiceReference.IGroupService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GroupServiceClient : System.ServiceModel.ClientBase<MaddalenaUnitTest.MaddalenaServiceReference.IGroupService>, MaddalenaUnitTest.MaddalenaServiceReference.IGroupService {
        
        public GroupServiceClient() {
        }
        
        public GroupServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GroupServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GroupServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GroupServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CreateGroup(string apiKey, MaddalenaUnitTest.MaddalenaServiceReference.Group group) {
            return base.Channel.CreateGroup(apiKey, group);
        }
        
        public System.Threading.Tasks.Task<bool> CreateGroupAsync(string apiKey, MaddalenaUnitTest.MaddalenaServiceReference.Group group) {
            return base.Channel.CreateGroupAsync(apiKey, group);
        }
        
        public MaddalenaUnitTest.MaddalenaServiceReference.Group ById(string apiKey, long groupid) {
            return base.Channel.ById(apiKey, groupid);
        }
        
        public System.Threading.Tasks.Task<MaddalenaUnitTest.MaddalenaServiceReference.Group> ByIdAsync(string apiKey, long groupid) {
            return base.Channel.ByIdAsync(apiKey, groupid);
        }
        
        public bool UpdateGroup(string apiKey, MaddalenaUnitTest.MaddalenaServiceReference.Group group) {
            return base.Channel.UpdateGroup(apiKey, group);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateGroupAsync(string apiKey, MaddalenaUnitTest.MaddalenaServiceReference.Group group) {
            return base.Channel.UpdateGroupAsync(apiKey, group);
        }
        
        public bool DeleteGroup(string apiKey, long groupid) {
            return base.Channel.DeleteGroup(apiKey, groupid);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteGroupAsync(string apiKey, long groupid) {
            return base.Channel.DeleteGroupAsync(apiKey, groupid);
        }
        
        public int GroupMembersCount(string apiKey, long groupid) {
            return base.Channel.GroupMembersCount(apiKey, groupid);
        }
        
        public System.Threading.Tasks.Task<int> GroupMembersCountAsync(string apiKey, long groupid) {
            return base.Channel.GroupMembersCountAsync(apiKey, groupid);
        }
        
        public MaddalenaUnitTest.MaddalenaServiceReference.User1[] GroupMembers(string apiKey, long groupid, int page) {
            return base.Channel.GroupMembers(apiKey, groupid, page);
        }
        
        public System.Threading.Tasks.Task<MaddalenaUnitTest.MaddalenaServiceReference.User1[]> GroupMembersAsync(string apiKey, long groupid, int page) {
            return base.Channel.GroupMembersAsync(apiKey, groupid, page);
        }
        
        public bool JoinGroup(string apiKey, long groupid) {
            return base.Channel.JoinGroup(apiKey, groupid);
        }
        
        public System.Threading.Tasks.Task<bool> JoinGroupAsync(string apiKey, long groupid) {
            return base.Channel.JoinGroupAsync(apiKey, groupid);
        }
        
        public void LeaveGroup(string apiKey, long groupid) {
            base.Channel.LeaveGroup(apiKey, groupid);
        }
        
        public System.Threading.Tasks.Task LeaveGroupAsync(string apiKey, long groupid) {
            return base.Channel.LeaveGroupAsync(apiKey, groupid);
        }
        
        public MaddalenaUnitTest.MaddalenaServiceReference.GroupPost[] Recents(string apiKey, long groupid) {
            return base.Channel.Recents(apiKey, groupid);
        }
        
        public System.Threading.Tasks.Task<MaddalenaUnitTest.MaddalenaServiceReference.GroupPost[]> RecentsAsync(string apiKey, long groupid) {
            return base.Channel.RecentsAsync(apiKey, groupid);
        }
        
        public MaddalenaUnitTest.MaddalenaServiceReference.GroupPost[] Tops(string apiKey, long groupid) {
            return base.Channel.Tops(apiKey, groupid);
        }
        
        public System.Threading.Tasks.Task<MaddalenaUnitTest.MaddalenaServiceReference.GroupPost[]> TopsAsync(string apiKey, long groupid) {
            return base.Channel.TopsAsync(apiKey, groupid);
        }
        
        public MaddalenaUnitTest.MaddalenaServiceReference.GroupPost[] List(string apiKey, long groupid, int page) {
            return base.Channel.List(apiKey, groupid, page);
        }
        
        public System.Threading.Tasks.Task<MaddalenaUnitTest.MaddalenaServiceReference.GroupPost[]> ListAsync(string apiKey, long groupid, int page) {
            return base.Channel.ListAsync(apiKey, groupid, page);
        }
        
        public MaddalenaUnitTest.MaddalenaServiceReference.GroupPost[] OfUser(string apiKey, long groupid, string userid, int page) {
            return base.Channel.OfUser(apiKey, groupid, userid, page);
        }
        
        public System.Threading.Tasks.Task<MaddalenaUnitTest.MaddalenaServiceReference.GroupPost[]> OfUserAsync(string apiKey, long groupid, string userid, int page) {
            return base.Channel.OfUserAsync(apiKey, groupid, userid, page);
        }
        
        public bool Post(string apiKey, MaddalenaUnitTest.MaddalenaServiceReference.GroupPost post1) {
            return base.Channel.Post(apiKey, post1);
        }
        
        public System.Threading.Tasks.Task<bool> PostAsync(string apiKey, MaddalenaUnitTest.MaddalenaServiceReference.GroupPost post) {
            return base.Channel.PostAsync(apiKey, post);
        }
        
        public bool Delete(string apiKey, long postId) {
            return base.Channel.Delete(apiKey, postId);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(string apiKey, long postId) {
            return base.Channel.DeleteAsync(apiKey, postId);
        }
        
        public bool Ban(string apiKey, long groupid, string username) {
            return base.Channel.Ban(apiKey, groupid, username);
        }
        
        public System.Threading.Tasks.Task<bool> BanAsync(string apiKey, long groupid, string username) {
            return base.Channel.BanAsync(apiKey, groupid, username);
        }
        
        public bool MakeModerator(string apiKey, long groupid, string username) {
            return base.Channel.MakeModerator(apiKey, groupid, username);
        }
        
        public System.Threading.Tasks.Task<bool> MakeModeratorAsync(string apiKey, long groupid, string username) {
            return base.Channel.MakeModeratorAsync(apiKey, groupid, username);
        }
        
        public bool MakeAdmin(string apiKey, long groupid, string username) {
            return base.Channel.MakeAdmin(apiKey, groupid, username);
        }
        
        public System.Threading.Tasks.Task<bool> MakeAdminAsync(string apiKey, long groupid, string username) {
            return base.Channel.MakeAdminAsync(apiKey, groupid, username);
        }
        
        public bool MakeOwner(string apiKey, long groupid, string username) {
            return base.Channel.MakeOwner(apiKey, groupid, username);
        }
        
        public System.Threading.Tasks.Task<bool> MakeOwnerAsync(string apiKey, long groupid, string username) {
            return base.Channel.MakeOwnerAsync(apiKey, groupid, username);
        }
    }
}
